### ISSUE TITLE
File metadata instead of item

### ISSUE THREAD

**Issue by apjmason** [DigitalCarleton/AccessibilityPlus#2]
Right now the plugin is pulling from the item metadata, which means you'll have content duplicated since it's displayed on the metadata once and also as alt text. Ideally, this should allow you to draw one one of the file metadata fields (title or alt title) to pull that into the item display.

**Comment by alexanderlewis99** [comment]
I have changed the code to pull from the file metadata. It will only pull from item metadata if the selected file metadata and the title metadata for files is missing. Have a good day.
